"""create oban tables

Revision ID: 62e0902657b1
Revises:
Create Date: 2025-03-05 17:19:59.514684

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "62e0902657b1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oban_jobs",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "available",
                "scheduled",
                "executing",
                "retryable",
                "completed",
                "discarded",
                "cancelled",
                name="oban_job_state",
            ),
            server_default="available",
            nullable=False,
        ),
        sa.Column("queue", sa.TEXT(), server_default="default", nullable=False),
        sa.Column("worker", sa.TEXT(), nullable=False),
        sa.Column("attempt", sa.SMALLINT(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.SMALLINT(), server_default="20", nullable=False),
        sa.Column("priority", sa.SMALLINT(), server_default="0", nullable=False),
        sa.Column(
            "args",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "meta",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "tags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "errors",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("attempted_by", sa.ARRAY(sa.TEXT()), nullable=False),
        sa.Column(
            "inserted_at",
            sa.TIMESTAMP(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "scheduled_at",
            sa.TIMESTAMP(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column("attempted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("cancelled_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("completed_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("discarded_at", sa.TIMESTAMP(), nullable=True),
        sa.CheckConstraint(
            "attempt >= 0 AND attempt <= max_attempts", name="attempt_range"
        ),
        sa.CheckConstraint("char_length(queue) > 0", name="queue_length"),
        sa.CheckConstraint("char_length(worker) > 0", name="worker_length"),
        sa.CheckConstraint("max_attempts > 0", name="positive_max_attempts"),
        sa.CheckConstraint("priority >= 0", name="non_negative_priority"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "oban_jobs_args_index",
        "oban_jobs",
        ["args"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "oban_jobs_meta_index",
        "oban_jobs",
        ["meta"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "oban_jobs_state_queue_priority_scheduled_at_id_index",
        "oban_jobs",
        ["state", "queue", "priority", "scheduled_at", "id"],
        unique=False,
    )
    op.create_table(
        "oban_peers",
        sa.Column("name", sa.TEXT(), nullable=False),
        sa.Column("node", sa.TEXT(), nullable=False),
        sa.Column("started_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("oban_peers")
    op.drop_index(
        "oban_jobs_state_queue_priority_scheduled_at_id_index", table_name="oban_jobs"
    )
    op.drop_index(
        "oban_jobs_meta_index", table_name="oban_jobs", postgresql_using="gin"
    )
    op.drop_index(
        "oban_jobs_args_index", table_name="oban_jobs", postgresql_using="gin"
    )
    op.drop_table("oban_jobs")
    # ### end Alembic commands ###
