INSERT INTO oban_jobs(
    args,
    attempt,
    attempted_at,
    attempted_by,
    cancelled_at,
    completed_at,
    discarded_at,
    errors,
    inserted_at,
    max_attempts,
    meta,
    priority,
    queue,
    scheduled_at,
    state,
    tags,
    worker
) VALUES (
    %(args)s,
    %(attempt)s,
    %(attempted_at)s,
    %(attempted_by)s,
    %(cancelled_at)s,
    %(completed_at)s,
    %(discarded_at)s,
    %(errors)s,
    coalesce(%(inserted_at)s, timezone('UTC', now())),
    %(max_attempts)s,
    %(meta)s,
    %(priority)s,
    %(queue)s,
    coalesce(%(scheduled_at)s, timezone('UTC', now())),
    %(state)s,
    %(tags)s,
    %(worker)s
) RETURNING id, inserted_at, scheduled_at;
